Feature/percentage input
pismo/bolt pull request #120
Opened 2020-09-17 12:54 UTC by HNunesO

# <Feature Title>

TESTS
**_#IMAGEM/GIF DE TESTES PASSANDO_**

PR RELACIONADA:
**_#ALGUMA PR RELACIONADA?_**

VALIDADO O BUILD?
**_#TESTADO NA MÁQUINA DO DESENVOLVEDOR MESMO PROCESSO DO CI?_**

DOCUMENTAÇÃO DE ENPOINT PARA VALIDAÇÃO:
**_#QUAL O LINK PARA DOCUMENTAÇÃO DOS ENDPOINTS CONSUMIDOS NESSA PR?_**

FORMATO DE DATAS?
**_#EM CASO DE EXEBIÇÃO DE DATAS, TODAS ESTÃO DE ACORDO COM O ESPERADO? HÁ CONVERSÃO DE HORA?_**

VALIDAÇÃO DE CAMPOS DE FORMULÁRIO?
**_#EM CASO DE ALTERAÇÃO OU CRIAÇÃO DE FORMULÁRIO, HÁ VALIDAÇÃO IMPLEMENTADA COMO ESPERADO? TESTE COBREM ERRO E SUCESSO?_**

I18N
**_#INTERNACIONALIZAÇÃO ESTÁ COBERTA?_**

MULTICURRENCY
**_#INTERNACIONALIZAÇÃO DE MOEDA ESTÁ COBERTA?_**

2020-09-23 21:32 UTC, viniciusavieira requested changes
Algumas considerações para debate e remover logs.
No geral está um trabalho muito bom e sólido.

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +      console.log('dentro do min')
Remover log

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +  function cursorToRight (target) {
Talvez seja válido deixar parametrizavel, em algumas situações testando o comportamento ficou estranho, não permitindo que apagasse alguns valores no campo.

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +  function cursorToRight (target) {
Um boolean na incialização do componente, para configurar essa funcionalidade.

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +    console.log(literal, 'teste literal')
Log

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +  lang?: Translation
Faz sentido internacionalização nesse ponto? É um componente que só tem 2 opções de renderização, com `,` ou com `.` e no que está na documentação não tem impacto trocar o idioma.

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +    num_str = new Intl.NumberFormat(translation[lang], {
Essa implementação parece muito sólida e robusta mas será que não estamos fazendo overengineering aqui?
Entendo que seria pegar o número, split('.').join('.') + '%'.
Há algum caso que necessita dessa implementação?

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +const translation = {
Necessário?

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +export type Translation = 'en' | 'pt' | 'es'
Necessário?

2020-09-23 21:32 UTC, viniciusavieira commented on packages/percentage-input/PercentInput.tsx
> +    num_str = new Intl.NumberFormat(translation[lang], {
`string.split('.').join(',') + '%'` ?

2020-09-24 22:33 UTC, HNunesO commented on packages/percentage-input/PercentInput.tsx
> +      console.log('dentro do min')
removido

2020-09-24 22:36 UTC, HNunesO commented on packages/percentage-input/PercentInput.tsx
> +  function cursorToRight (target) {
Essa função foi retirada por que adicionado casas decimais o mouse se move para direita automaticamente

2020-09-24 22:36 UTC, HNunesO commented on packages/percentage-input/PercentInput.tsx
> +    console.log(literal, 'teste literal')
removido

2020-09-24 22:43 UTC, HNunesO commented on packages/percentage-input/PercentInput.tsx
> +  lang?: Translation
Examinando melhor o funcionamento do componente, resolvi enxugar o código retirando a internacionalização e deixando a função de troca de pontuação por virgula recebendo true ou false.

2020-09-24 22:43 UTC, HNunesO commented on packages/percentage-input/PercentInput.tsx
> +    num_str = new Intl.NumberFormat(translation[lang], {
mesma situação do comentario anterior

2020-09-24 22:44 UTC, HNunesO commented on packages/percentage-input/PercentInput.tsx
> +const translation = {
retirado

2020-09-24 22:44 UTC, HNunesO commented on packages/percentage-input/PercentInput.tsx
> +export type Translation = 'en' | 'pt' | 'es'
retirado

2020-09-28 18:27 UTC, abraaobuenotype approved these changes
Aprovando, pois o comportamento geral está OK, mas o backspace não está intuitivo, o componente precisará de um update futuramente

2020-09-29 17:56 UTC, merged

2020-10-02 12:45 UTC, HNunesO commented
Nesse novo commit, corrige o problema do backspace ou delete de numeros vindo da direita para esquerda